
# 

# Numba For CUDA GPU: A Quick Guide
---

### Target Audience
This quick guide targets python developers who are interested in developing HPC applications using CUDA accelerated Python library on the GPU.

### Objectives
- **The objectives of this guide are to:**
    -   quickly get you started with Numba from beginner to advanced level
    -   teach you application of CUDA GPU programming concept in HPC field(s)
    -   show you how to maximize the throughput of your HPC implementation through computational speedup on the GPU.  

### Outline
   1. Introduction
   2. Installation Guide
   3. Definition of Terms
   4. CUDA Kernels
   5. Memory Management
   6. Atomic Operation
   7. CUDA UFuncs
   8. Summary
   9. HPC Approach
     



### 1. Introduction
- Numba is a just-in-time (jit) compiler for Python that works best on code that uses NumPy arrays, functions, and loops. Numba has set of decorators that can be specified before user-defined functions to determine how they are compiled.  
- A decorated function written in python is compiled into CUDA kernel to speed up execution rate, thus, Numba supports CUDA GPU programming model. 
- A kernel is written in Numba automatically have direct access to NumPy arrays. This implies a great support for data visiblilty between the host (CPU) and the device (GPU). 

### 2. Installation Guide
- OS: 
    support Windows (32 and 64 bit) and Linux (32 and 64 bit)
- Numba is available as a conda package for the Anaconda Python distribution:
    - conda install cudatoolkit 
    - conda install numba
- Numba also has wheels available:
    - pip install numba

### 3. Definition of Terms
- The CPU is called a **Host**.  
- The GPU is called a **Device**.
- A GPU function launched by the host and executed on the device is called a **Kernels**.
- A GPU function executed on the device which can only be called from the device is called a **Device function**.

### Note
- It is recommended to visit the NVIDIA official documentary web page and read through [CUDA C programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide), because most CUDA programming features exposed by Numba map directly to the CUDA C language offered by NVidia. 
- Numba does not implement of these CUDA features of CUDA:
     - dynamic parallelism
     - texture memory

## 4. CUDA Kernel
- In CUDA, written code can be executed by hundreds or thousands of threads at a single run, hence, a solution is modeled after the following thread hierarchy: 
    - **Grid**: A kernel executed as a collection of blocks 
    - **Thread Block**: Collection of threads that can communicate via a shared memory. Each thread is executed by a core.
    - **Thread**: Single execution units that run kernels on GPU.
- Numba exposes three kinds of GPU memory: 
    - global device memory  
    - shared memory 
    - local memory. 
- Memory access should be carefully considered in order to keep bandwidth contention at minimal.

 <img src="../images/thread_blocks.JPG"/> <img src="../images/memory_architecture.png"/> 

### Kernel Declaration
- A kernel function is a GPU function that is called from a CPU code by specifying the number of block threads and threads per block, and can not explicitly return a value except through a passed array. 
- A kernel can be called multiple times with varying number of blocks per grid and threads per block after its has been compiled once.

Example:

```python
@cuda.jit
def arrayAdd(array_A, array_B, array_out):
    #...code body ...
```
###### Kernel Invocation
- A kernel is typically launched in the following way:
```python
threadsperblock = 128
N = array_out.size
blockspergrid = ( N + (threadsperblock - 1))// threadsperblock
arrayAdd[blockspergrid, threadsperblock](array_A, array_B, array_out)
```

###### Choosing Block Size
- The block size determines how many threads share a given area of shared memory.
- The block size must be large enough to accommodate all computation units. See more details [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/).

### Thread Positioning 
- When running a kernel, the kernel function’s code is executed by every thread once. Hence is it important to uniquely identify distinct threads.
- The default way to determine a thread position in a grid and block is to manually compute the corresponding array position:


<img src="../images/thread_position.png"/>


```python
threadsperblock = 128
N = array_out.size

@cuda.jit
def arrayAdd(array_A, array_B, array_out):
    tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
    if tid < N: #Check array boundaries
        array_out[tid] =  array_A[tid] + array_B[tid]

#Unless you are sure the block size and grid size are a divisor of your array size, you must check boundaries as shown in the code block above. 
```
### Example 1: Addition on 1D-Arrays


In [1]:
import numba.cuda as cuda
import numpy as np

N = 500000
threadsperblock = 1000

@cuda.jit()
def arrayAdd(array_A, array_B, array_out):
    tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
    if tid < N:
        array_out[tid] = array_A[tid] + array_B[tid]


        
array_A = np.arange(N, dtype=np.int)
array_B = np.arange(N, dtype=np.int)
array_out = np.zeros(N, dtype=np.int)

blockpergrid  = N + (threadsperblock - 1) // threadsperblock

arrayAdd[blockpergrid, threadsperblock](array_A, array_B, array_out)

print("result: {} ".format(array_out))

result: [     0      2      4 ... 999994 999996 999998] 


**From Example 1:** 
> - N is the size of the array and the number of threads in a single block is 128.
> - The **cuda.jit()** decorator indicates that the function (arrayAdd) below is a device kernel and should run parallel. The **tid** is the estimate of a unique index for each thread in the device memory grid: 
>> **tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x**.
> - **array_A** and **array_B** are input data, while **array_out** is output array and is already preload with zeros.
> - The statement **blockpergrid  = N + (threadsperblock - 1) // threadsperblock** Computes the size of block per grid. This line of code is commonly use as the default formular to estimate number of blocks per grid in several GPU programming documentations.
> - **arrayAdd[blockpergrid, threadsperblock](array_A, array_B, array_out)** indicate a call to a kernel function **addAdd** having the number of blocks per grid and number of threads per block in square bracket, while kernel arguments are in round brackets.




###  Matrix multiplication on 2D Array 

<img src="../images/2d_array.png"/>

<img src="../images/2d_col_mult.png"/>

> **Note**
> - **Approach 2** would not be possible if the matrix size exceed the maximum number of threads per block on the device, while **Approach 1** would continue to execute. Most latest GPUs have maximum of 1024 threads per thread block. 

### Example 2:  Matrix multiplication 

In [2]:
import numba.cuda as cuda
import numpy as np
import math

N = 4
@cuda.jit()
def MatrixMul2D(array_A, array_B, array_out):
   row, col = cuda.grid(2)
   if row < array_out.shape[0] and col < array_out.shape[1]:
      for k in range(N):
         array_out[row][col]+= array_A[row][k] * array_B[k][col]


array_A   = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2],[3,3,3,3]], dtype=np.int)
array_B   = np.array([[0,1,2,3],[0,1,2,3],[0,1,2,3],[0,1,2,3]], dtype=np.int)
array_out = np.zeros(N*N, dtype=np.int).reshape(N, N)

threadsperblock = (2,2)
blockpergrid_x  = (math.ceil( N / threadsperblock[0]))
blockpergrid_y  = (math.ceil( N / threadsperblock[1]))
blockpergrid    = (blockpergrid_x, blockpergrid_y)

MatrixMul2D[blockpergrid,threadsperblock](array_A, array_B, array_out)

print("array_A:\n {}\n".format(array_A))
print("array_B:\n {}\n".format(array_B))
print("array_A * array_B:\n {}".format(array_out))

#Note
#The cuda.grid() returns the thread ID in X and Y (row & col) direction of the memory grid


array_A:
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]

array_B:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

array_A * array_B:
 [[ 0  0  0  0]
 [ 0  4  8 12]
 [ 0  8 16 24]
 [ 0 12 24 36]]


### Exaample 3: A 225 × 225 Matrix Multiplication

In [3]:
N = 225

@cuda.jit()
def MatrixMul2D(array_A, array_B, array_out):
   x, y = cuda.grid(2)
   if x < array_out.shape[0] and y < array_out.shape[1]:
      for k in range(N):
         array_out[x][y] += array_A[x][k] * array_B[k][y]

threadsperblock = (25,25)
array_A = np.arange((N*N), dtype=np.int).reshape(N,N)
array_B = np.arange((N*N), dtype=np.int).reshape(N,N)
array_out = np.zeros((N*N), dtype=np.int).reshape(N,N)

blockpergrid_x  = (math.ceil( N / threadsperblock[0]))
blockpergrid_y  = (math.ceil( N / threadsperblock[1]))
blockpergrid    = (blockpergrid_x, blockpergrid_y)

MatrixMul2D[blockpergrid,threadsperblock](array_A, array_B, array_out)

print(array_out)

[[  848610000   848635200   848660400 ...   854204400   854229600
    854254800]
 [ 2124360000  2124435825  2124511650 ...  2141193150  2141268975
   2141344800]
 [ -894857296  -894730846  -894604396 ...  -866785396  -866658946
   -866532496]
 ...
 [  597268464   608532414   619796364 ... -1197101932 -1185837982
  -1174574032]
 [ 1873018464  1884333039  1895647614 ...    89886818   101201393
    112515968]
 [-1146198832 -1134833632 -1123468432 ...  1376875568  1388240768
   1399605968]]


### Thread reuse 

- It is possible to specify a few number of threads for a data size such that threads are reused to complete the computation of the entire data. This is one of the approach used when a data to be computed is larger than the maximum number of threads available in a device memory. 
- This statement is used in a while loop: ***tid += cuda.blockDim.x * cuda.gridDim.x***
- An example is given below to illustrates thread reuse. In the example, small number of thread is specified on purpose in order to show the possibility of this approach. 


#### Example 4: 

In [4]:
import numba.cuda as cuda
import numpy as np

N = 500000
threadsperblock = 1000

@cuda.jit
def arrayAdd(array_A, array_B, array_out):
   tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
   while tid < N:
      array_out[tid] = array_A[tid] + array_B[tid]
      tid += cuda.blockDim.x * cuda.gridDim.x

array_A = np.arange(N, dtype=np.int)
array_B = np.arange(N, dtype=np.int)
array_out = np.zeros(N, dtype=np.int)

arrayAdd[1, threadsperblock](array_A, array_B, array_out)

print("result: {} ".format(array_out))



result: [     0      2      4 ... 999994 999996 999998] 


> **Note**
> - The task in **example 4** is the same as in **example 1** but with limited number of threads specified, howbeit, the same result was achieved. 
> - Note that this approach may delegate more threads than required. In the code above, an excess of 1 block of threads may be delegated.


## 5. Memory Management

### Data Transfer 
- When a kernel is excuted, Numba automatically transfer NumPy arrays to the device and vice versa.
- In order to avoid the unnecessary transfer for read-only arrays, the following APIs can be used to manually control the transfer.

##### 1.  Copy host to device
```python
import numba.cuda as cuda
import numpy as np

N = 500000
h_A = np.arange(N, dtype=np.int)
h_B = np.arange(N, dtype=np.int)
h_C = np.zeros(N, dtype=np.int)

d_A = cuda.to_device(h_A)
d_B = cuda.to_device(h_B)
d_C = cuda.to_device(h_C)
```
##### 2.  Enqueue the transfer to a stream
```python
h_A    = np.arange(N, dtype=np.int)
stream = cuda.stream()
d_A    = cuda.to_device(h_A, stream=stream)
```
##### 3.  Copy device to host / enqueue the transfer to a stream 
```python
h_C = d_C.copy_to_host()
h_C = d_C.copy_to_host(stream=stream)
```
### Example 5:  data movement 

In [5]:
import numba.cuda as cuda
import numpy as np
N = 200
threadsperblock = 25

@cuda.jit
def arrayAdd(d_A, d_B, d_C):
   tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
   if tid < N:
      d_C[tid] = d_A[tid] + d_B[tid]
      
h_A = np.arange(N, dtype=np.int)
h_B = np.arange(N, dtype=np.int)
h_C = np.zeros(N, dtype=np.int)

d_A = cuda.to_device(h_A)
d_B = cuda.to_device(h_B)
d_C = cuda.to_device(h_C)

blockpergrid  = N + (threadsperblock - 1) // threadsperblock
arrayAdd[blockpergrid, threadsperblock](d_A, d_B, d_C)

h_C = d_C.copy_to_host()
print(h_C)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398]


## 6. Atomic Operation

- Atomic operation is required in a situation where multiple threads attempt to modify a common portion of the memory. 
- Typical example includes: simultaneous withdrawal from a bank account through ATM machine or large number of threads modfying a particular index of an array based on certain condition(s)
- List of presently implemented atomic operations supported by Numba are:
> **import numba.cuda as cuda**
> - cuda.atomic.add(array, index, value)
> - cuda.atomic.min(array, index, value)
> - cuda.atomic.max(array, index, value)
> - cuda.atomic.nanmax(array, index, value)
> - cuda.atomic.nanmin(array, index, value)
> - cuda.atomic.compare_and_swap(array, old_value, current_value)
> - cuda.atomic.sub(array, index, value)

In [6]:
# Task ==> sum of an array: [1,2,3,4,5,6,7,8,9,10] in parallel
# Note that threads are executed randomly

# atomic operation example 
size = 10
nthread = 10
@cuda.jit()
def add_atomic(my_array, total):
   tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
   cuda.atomic.add(total,0, my_array[tid])

my_array = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int32)
total = np.zeros(1, dtype=np.int32)
nblock = int(size / nthread)
add_atomic[nblock, nthread](my_array, total)
print("Atomic:", total)

######################################################################################
# Non-atomic operation example  
size = 10
nthread = 10
@cuda.jit()
def add_atomic(my_array, total):
   tid = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
   total[0] += my_array[tid]
   

my_array = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int32)
total = np.zeros(1, dtype=np.int32)
nblock = int(size / nthread)
add_atomic[nblock, nthread](my_array, total)
print("Non atomic: ", total)



Atomic: [55]
Non atomic:  [1]


## Device Management

#### Multi-GPU

- During computation, the CUDA driver selects the fastest GPU as the device 0 by default. One can also select other GPUs manually or temporarily.

```python
import numba.cuda as cuda
cuda.select_device(0)
..............
Cuda.close()#close device 0


Cuda.select_device(1)
..............

Cuda.close()#close device 1
```

#### Device List
- The Device List (**cuda.gpus**) list all the existing GPUs in a machine (workstation) and can be indexed using (**with cuda.gpus[ ]**) to ensure execution on a particluar GPU. 

In [7]:
import numba.cuda as cuda

print(cuda.gpus)
print(cuda.gpus[0])

with cuda.gpus[0]:
    print("gpu 0 selected" )

<Managed Device 0>
<Managed Device 0>
gpu 0 selected


### 7. CUDA Ufuncs

- The CUDA ufunc supports passing intra-device arrays to reduce traffic over the PCI-express bus. 
- It also support asynchronous mode by using stream keyword.

<img src="../images/ufunc.png"/>

In [8]:
from numba import vectorize
import numba.cuda as cuda
import numpy as np

@vectorize(['float32(float32, float32)'],target='cuda')
def compute(a, b):
    return (a - b) * (a + b)

N = 10000
A = np.arange(N , dtype=np.float32)
B = np.arange(N, dtype=np.float32)
C = compute(A, B)

print(C.reshape(100,100))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### Device function

- The CUDA device functions can only be invoked from within the device and can return a value like normal functions. The device function is usually placed before the CUDA ufunc kernel otherwise a call to the device function may not be visible inside the ufunc kernel.

In [9]:
from numba import vectorize
import numba.cuda as cuda
import numpy as np
import math

@cuda.jit('float32(float32)', device=True, inline=True)
def device_ufunc(c):
   return math.sqrt(c)

@vectorize(['float32(float32, float32)'],target='cuda')
def compute(a, b):
    c = (a - b) * (a + b)
    return device_ufunc(c)


## 8. Summary

<img src="../images/numba_summary1.png"/>


---
<div style="text-align:center; color:#FF0000"><b>Click on HPC Approach Link to view task on HPC serial code</b> </div>

## 9. [HPC Approach](serial_RDF.ipynb)

---


## References

- Numba Documentation, Release 0.52.0-py3.7-linux-x86_64.egg, Anaconda, Nov 30, 2020.
- Bhaumik Vaidya, Hands-On GPU-Accelerated Computer Vision with OpenCV and CUDA, Packt Publishing, 2018.
- https://docs.nvidia.com/cuda/cuda-c-programming-guide/


--- 

## Licensing 

This material is released by NVIDIA Corporation under the Creative Commons Attribution 4.0 International (CC BY 4.0).